-maxapiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    app: memcached
spec:
  ports:
  - port: {{ .Values.memcachedPort }}
    protocol: TCP
    targetPort: {{ .Values.memcachedPort }}
  selector:
    app: memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: {{ .Values.memcachedReplicas }}
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
      annotations:
        roll-update-timestamp: {{ now | quote }}
    spec:
      containers:
        - image: ghcr.io/rnacentral/memcached:1.6.7-alpine
          name: memcached
          resources:
            requests:
              memory: {{ .Values.memcachedRequestsMemory }}
              cpu: {{ .Values.memcachedRequestsCPU }}
            limits:
              memory: {{ .Values.memcachedLimitsMemory }}
          args:
            - "-m"
            - "{{ .Values.memcachedServiceMemory }}"
            - "-p"
            - "{{ .Values.memcachedPort }}"
            - "-I"
            - "1m"
          ports:
            - containerPort: {{ .Values.memcachedPort }}
      restartPolicy: Always
