apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - port: {{ .Values.redisPort }}
    protocol: TCP
    targetPort: {{ .Values.redisPort }}
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: {{ .Values.redisReplicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:6.0.8-alpine
          name: redis
          resources:
            requests:
              memory: {{ .Values.redisRequestsMemory }}
              cpu: {{ .Values.redisRequestsCPU }}
            limits:
              memory: {{ .Values.redisLimitsMemory }}
          args:
            - "--port {{ .Values.redisPort }}"
          ports:
            - containerPort: {{ .Values.redisPort }}
      restartPolicy: Always
