apiVersion: v1
kind: Service
metadata:
  name: rnacentral
  labels:
    app: rnacentral
spec:
  type: NodePort  # EBI asked to expose the service using NodePort
  ports:
  - port: {{ .Values.rnacentralPort }}
    targetPort: {{ .Values.rnacentralPort }}
    protocol: TCP
  selector:
    app: rnacentral
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rnacentral
spec:
  replicas: {{ .Values.rnacentralReplicas }}
  selector:
    matchLabels:
      app: rnacentral
  template:
    metadata:
      labels:
        app: rnacentral
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - image: rnacentral/rnacentral-webcode:{{ .Values.rnacentralBranch }}
          name: rnacentral
          imagePullPolicy: Always
          ports:
          - containerPort: {{ .Values.rnacentralPort }}
          resources:
            requests:
              memory: {{ .Values.rnacentralRequestsMemory }}
              cpu: {{ .Values.rnacentralRequestsCPU }}
            limits:
              memory: {{ .Values.rnacentralLimitssMemory }}
              cpu: {{ .Values.rnacentralLimitsCPU }}
          volumeMounts:
            - name: static-volume
              mountPath: /srv/rnacentral/static
            - name: rnacentral-species-specific-ids
              mountPath: /srv/rnacentral/fasta
            - name: export-results
              mountPath: /srv/rnacentral/export
            {{- if eq .Values.sitemaps "true" }}
            - name: sitemaps
              mountPath: /srv/rnacentral/rnacentral-webcode/rnacentral/sitemaps
            - name: sitemaps-config
              mountPath: /srv/rnacentral/rnacentral-webcode/sitemaps.sh
              subPath: sitemaps.sh
            {{- end }}
            {{- if eq .Values.webComponents "true" }}
            - name: web-components
              mountPath: /srv/rnacentral/rnacentral-webcode/web-components.sh
              subPath: web-components.sh
            {{- end }}
          env:
            - name: RNACENTRAL_ENV
              value: {{ .Values.setEnv }}
          envFrom:
          - secretRef:
              name: {{ .Values.database }}
          - secretRef:
              name: s3
          - configMapRef:
              name: {{ .Values.proxy }}
          - configMapRef:
              name: {{ .Values.searchIndex }}
      restartPolicy: Always
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-volume
        - name: rnacentral-species-specific-ids
          persistentVolumeClaim:
            claimName: rnacentral-species-specific-ids
        - name: export-results
          persistentVolumeClaim:
            claimName: export-results
        {{- if eq .Values.sitemaps "true" }}
        - name: sitemaps
          persistentVolumeClaim:
            claimName: sitemaps
        - name: sitemaps-config
          configMap:
            name: sitemaps-config
            defaultMode: 0755
        {{- end }}
        {{- if eq .Values.webComponents "true" }}
        - name: web-components
          configMap:
            name: web-components
            defaultMode: 0755
        {{- end }}
