apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    app: memcached
spec:
  ports:
  - port: 8052
    protocol: TCP
    targetPort: 8052
    name: memcached-8052
  selector:
    app: memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - image: memcached:1.6.7-alpine
          name: memcached
          resources:
            requests:
              memory: "1024Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "500m"
          args:
            - '-m 2048 -p 8052'
          ports:
            - containerPort: 8052
      restartPolicy: Always