stages:
  - deploy

.deploy_steps: &deploy_steps
  script:
    - kubectl config use-context RNAcentral/rnacentral-webcode:$AGENT
    - kubectl config set-context --current --namespace=$NAMESPACE
    - cd kubernetes/helm
    - helm uninstall full-$NAMESPACE --namespace $NAMESPACE
    - sleep 10
    - helm upgrade --install full-$NAMESPACE --namespace $NAMESPACE --values=$VALUES_FILE --set proxy=$PROXY,database=$DATABASE,searchIndex=$SEARCH_INDEX,rnacentralBranch=$RNACENTRAL_BRANCH,rnacentralReplicas=$RNACENTRAL_REPLICAS .

.variables_hx: &variables_hx
  variables:
    AGENT: "agent-hx"
    NAMESPACE: "prod"
    VALUES_FILE: "values.yaml"
    PROXY: "proxy-hx"
    DATABASE: "db-fb"
    SEARCH_INDEX: "search-index-prod"
    RNACENTRAL_BRANCH: "master"
    RNACENTRAL_REPLICAS: "1"

.variables_hh: &variables_hh
  variables:
    AGENT: "agent-hh"
    NAMESPACE: "dev"
    VALUES_FILE: "values.dev.yaml"
    PROXY: "proxy-hh"
    DATABASE: "db-pro"
    SEARCH_INDEX: "search-index-dev"
    RNACENTRAL_BRANCH: "$CI_COMMIT_REF_NAME"  # use the branch that triggered the pipeline
    RNACENTRAL_REPLICAS: "1"

# Automatic deployment to the fallback website when the master branch is updated
fallback_prod_website:
  stage: deploy
  image:
    name: rnacentral/rnacentral-ci-cd
  <<: [*deploy_steps, *variables_hx]
  only:
    refs: [ master ]
    changes:
      - rnacentral/**/*

# Automatic deployment to the testing website when any branch is updated
test_website:
  stage: deploy
  image:
    name: rnacentral/rnacentral-ci-cd
  <<: [*deploy_steps, *variables_hh]
  only:
    changes:
      - rnacentral/**/*

# Manual deployment to HX cluster
cluster_hx_manual:
  stage: deploy
  image:
    name: rnacentral/rnacentral-ci-cd
  <<: [*deploy_steps, *variables_hx]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $DC == "hx"'
      when: manual

# Manual deployment to HH cluster
cluster_hh_manual:
  stage: deploy
  image:
    name: rnacentral/rnacentral-ci-cd
  <<: [*deploy_steps, *variables_hh]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $DC == "hh"'
      when: manual
