stages:
#  - test
#  - build
  - deploy

#test_image:
#  image: python:3.8.15-slim
#  stage: test
#  before_script:
#    - |
#      apt-get update && apt-get install -y --no-install-recommends \
#      g++ \
#      build-essential \
#      tar \
#      git \
#      && rm -rf /var/lib/apt/lists/*
#    - python -m pip install --upgrade pip
#    - pip install -r rnacentral/requirements.txt
#    - pip install -r rnacentral/requirements_dev.txt
#    - mv rnacentral/rnacentral/unit_test_local_settings.py rnacentral/rnacentral/local_settings.py
#  script:
#    - |
#      python rnacentral/manage.py test apiv1
#      python rnacentral/manage.py test export
#      python rnacentral/manage.py test portal
#      python rnacentral/manage.py test sequence_search

#build_image:
#  stage: build
#  variables:
#    DOCKER_USER: $DOCKER_USER
#    DOCKER_PASSWORD: $DOCKER_PASSWORD
#  before_script:
#    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#  script:
#    - docker build -f Dockerfile -t rnacentral/rnacentral-webcode:${CI_COMMIT_BRANCH} .
#    - docker push rnacentral/rnacentral-webcode:${CI_COMMIT_BRANCH}

deploy_image:
  stage: deploy
  image:
    name: bitnami/kubectl:1.23.15
    entrypoint: [""]
  script:
    - echo "$CI_COMMIT_BRANCH"
    - kubectl config use-context RNAcentral/rnacentral-webcode:primary-agent
    - kubectl config set-context --current --namespace=prod
    - POD=`kubectl get pod -l app=memcached -o jsonpath="{.items[0].metadata.name}"`
    - kubectl exec -it "$POD" -- sh -c "echo flush_all | nc localhost 11211"
