stages:
  - test
  - build
  - deploy

test_image:
  image: python:3.8.15-slim
  stage: test
  before_script:
    - |
      apt-get update && apt-get install -y --no-install-recommends \
      g++ \
      build-essential \
      tar \
      git \
      && rm -rf /var/lib/apt/lists/*
    - python -m pip install --upgrade pip
    - pip install -r rnacentral/requirements.txt
    - pip install -r rnacentral/requirements_dev.txt
    - mv rnacentral/rnacentral/unit_test_local_settings.py rnacentral/rnacentral/local_settings.py
  script:
    - |
      python rnacentral/manage.py test apiv1
      python rnacentral/manage.py test export
      python rnacentral/manage.py test portal
      python rnacentral/manage.py test sequence_search

build_image:
  stage: build
  variables:
    DOCKER_USER: $DOCKER_USER
    DOCKER_PASSWORD: $DOCKER_PASSWORD
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - echo "BRANCH_NAME=$(echo ${CI_COMMIT_REF_NAME} | tr / -)" >> .env
    - export $(cat .env | xargs)
    - docker build -f Dockerfile -t rnacentral/rnacentral-webcode:${BRANCH_NAME} .
    - docker push rnacentral/rnacentral-webcode:${BRANCH_NAME}
  artifacts:
    reports:
      dotenv: .env

deploy_image:
  stage: deploy
  image:
    name: bitnami/kubectl:1.29.4
    entrypoint: [""]
  script:
    - echo "$BRANCH_NAME"
    - kubectl config get-contexts
    - kubectl config use-context gitlab-agent
    - kubectl get pods --namespace dev
