stages:
  - test

test:
  image: python:3.8.15-slim
  stage: test
  before_script:
    - |
      apt-get update && apt-get install -y --no-install-recommends \
      g++ \
      build-essential \
      tar \
      git \
      && rm -rf /var/lib/apt/lists/*
    - python -m pip install --upgrade pip
    - pip install -r rnacentral/requirements.txt
    - pip install -r rnacentral/requirements_dev.txt
    - mv rnacentral/rnacentral/unit_test_local_settings.py rnacentral/rnacentral/local_settings.py
  script:
    - python rnacentral/manage.py test apiv1
