stages:
  - deploy

cluster_hx:
  stage: deploy
  image:
    name: rnacentral/rnacentral-ci-cd
  variables:
    NAMESPACE: "prod"
    PROXY: "proxy-hx"
    DATABASE: "db-fb"
    SEARCH_INDEX: "search-index-prod"
    RNACENTRAL_BRANCH: "master"
    RNACENTRAL_REPLICAS: "1"
  script:
    - kubectl config use-context RNAcentral/rnacentral-webcode:primary-agent
    - kubectl config set-context --current --namespace=$NAMESPACE
    - cd kubernetes/helm
    - helm uninstall full-$NAMESPACE --namespace $NAMESPACE
    - sleep 10
    - helm upgrade --install full-$NAMESPACE --namespace $NAMESPACE --set proxy=$PROXY,database=$DATABASE,searchIndex=$SEARCH_INDEX,rnacentralBranch=$RNACENTRAL_BRANCH,rnacentralReplicas=$RNACENTRAL_REPLICAS .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
#      changes:
#        - rnacentral/*
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual

cluster_hh:
  stage: deploy
  image:
    name: rnacentral/rnacentral-ci-cd
  variables:
    NAMESPACE: "dev"
    PROXY: "proxy-hh"
    DATABASE: "db-pro"
    SEARCH_INDEX: "search-index-dev"
    RNACENTRAL_BRANCH: "master"
    RNACENTRAL_REPLICAS: "1"
  script:
    - kubectl config use-context RNAcentral/rnacentral-webcode:agent-hh
    - kubectl config set-context --current --namespace=$NAMESPACE
    - cd kubernetes/helm
    - helm uninstall full-$NAMESPACE --namespace $NAMESPACE
    - sleep 10
    - helm upgrade --install full-$NAMESPACE --namespace $NAMESPACE -values=values.dev.yaml --set proxy=$PROXY,database=$DATABASE,searchIndex=$SEARCH_INDEX,rnacentralBranch=$RNACENTRAL_BRANCH,rnacentralReplicas=$RNACENTRAL_REPLICAS .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
#      changes:
#        - rnacentral/*
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual
