language: python
python:
  - "2.7"
# install dependencies
install:
  - "pip install requests selenium"
# run tests
script:
  - travis_wait python rnacentral/portal/tests/selenium_tests.py --base_url=http://rnacentral.org --driver=phantomjs
# define branches
branches:
  only:
    - master
