language: python
python:
  - "2.7"
# install dependencies
install:
  - "pip install requests selenium django djangorestframework django-cors-headers django-debug-toolbar django-compressor django-markdown-deux django-rq django-filter"
  - "pip install -e git+https://github.com/jbalogh/django-cache-machine.git@f827f05b195ad3fc1b0111131669471d843d631f#egg=django_cache_machine-dev"
# run tests
script:
  - python rnacentral/apiv1/tests.py --base_url=http://test.rnacentral.org
  - python rnacentral/portal/tests/selenium_tests.py --base_url=http://test.rnacentral.org --driver=phantomjs
# define branches
branches:
  only:
    - master
env: RNACENTRAL_SECRET_KEY='normally_set_in_local_settings.py'
