language: python
python:
  - "2.7"
# install dependencies
install: pip install requests selenium django
# run tests
script:
    - python rnacentral/apiv1/tests.py --base_url=http://test.rnacentral.org
    - python rnacentral/portal/tests/selenium_tests.py --base_url=http://test.rnacentral.org --driver=phantomjs
# define branches
branches:
  only:
    - master
env: RNACENTRAL_SECRET_KEY='normally_set_in_local_settings.py'
