#-------------------------------------------------------------------------------
# To avoid rate limit issues with GitLab and DockerHub, push the memcached image to GHCR.
# Current GHCR limit:
# - 100 pulls per 6 hours per IP address for anonymous users.
# - Unlimited pulls for users authenticated with a GitHub account and a valid PAT
#
# Commands to build and push:
#
# docker buildx create --use
# docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/rnacentral/memcached:1.6.7-alpine -f Dockerfile-memcached --push .
#
#-------------------------------------------------------------------------------
FROM memcached:1.6.7-alpine
