version: '3'

services:
  # RNAcentral website
  rnacentral:
    build:
      context: .
      args:
        - LOCAL_DEVELOPMENT=${LOCAL_DEVELOPMENT}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - S3_HOST=${S3_HOST}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
    expose:
      - 8000
    volumes:
      - static_volume:/srv/static
      - ./openssl/openssl.cnf:/etc/ssl/openssl.cnf
    depends_on:
      - redis
    networks:
      - redis-network
      - nginx-network
      - memcached-network

  # Redis server
  redis:
    image: redis:6.0.8-alpine
    ports:
      - 8051:8051
    command: redis-server --port 8051
    restart: always
    networks:
      - redis-network

  # Nginx server
  nginx:
    image: nginx:1.20-alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/srv/static
    depends_on:
      - rnacentral
    networks:
      - nginx-network

  # Memcached server
  memcached:
    image: memcached:1.6.7-alpine
    ports:
      - 8052:8052
    command: memcached -m 512m -p 8052
    depends_on:
      - rnacentral
    networks:
      - memcached-network

volumes:
  static_volume:

networks:
  redis-network:
    driver: bridge
  nginx-network:
    driver: bridge
  memcached-network:
    driver: bridge