version: '2'

services:
  # RNAcentral website
  web:
    build:
      context: .
      dockerfile: Dockerfile-development
    volumes:
      - "rnacentral_data:/rnacentral"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
    stdin_open: true
    tty: true
    ports:
      - "9000:8000"
    depends_on:
      - redis
    networks:
      node_net:
        ipv4_address: 192.168.1.2

  # Redis server
  redis:
    image: "redis:alpine"
    ports:
      - "8051:8051"
    command: redis-server --port 8051
    restart: always
    networks:
      node_net:
        ipv4_address: 192.168.1.3

volumes:
  rnacentral_data:

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24