#------------------------------------------------------------------------------
# We have 2 ways to deploy RNAcentral in production:
# bare-metal managed (no root permissions) CentOS 6 VMs and Kubernetes.
#
# This Dockerfile is meant for containerized deployment with Kubernetes.
#
#-------------------------------------------------------------------------------

FROM debian:latest

RUN apt-get update && apt-get install -y \
    g++ \
    build-essential \
    curl \
    wget \
    tar \
    git \
    python2.7 \
    libpython2.7-dev \
    python-pip \
    redis-server \
    memcached

ADD . /srv/rnacentral
RUN mkdir /srv/rnacentral/local
RUN mkdir /srv/rnacentral/static

ENV RNACENTRAL_LOCAL /srv/rnacentral/local
ENV RNACENTRAL_HOME /srv/rnacentral

# Install Infernal
RUN \
    cd $RNACENTRAL_LOCAL && \
    curl -OL http://eddylab.org/infernal/infernal-1.1.1.tar.gz && \
    tar -xvzf infernal-1.1.1.tar.gz && \
    cd infernal-1.1.1 && \
    ./configure --prefix=$RNACENTRAL_LOCAL/infernal-1.1.1 && \
    make && \
    make install && \
    cd easel && \
    make install && \
    cd $RNACENTRAL_LOCAL && \
    rm infernal-1.1.1.tar.gz

# Install Django requirements
RUN pip install -r /srv/rnacentral/rnacentral/requirements.txt

# Install node.js
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs

# Install node.js dependencies
ADD rnacentral/portal/static/package.json $RNACENTRAL_HOME/rnacentral/portal/static/
RUN cd $RNACENTRAL_HOME/rnacentral/portal/static && npm install --only=production

# Start up the app
ENTRYPOINT python /srv/rnacentral/rnacentral/manage.py runserver 0.0.0.0:8000
