#-------------------------------------------------------------------------------
# To avoid rate limit issues with GitLab and DockerHub, push the CI-CD image to GHCR.
# Current GHCR limit:
# - 100 pulls per 6 hours per IP address for anonymous users.
# - Unlimited pulls for users authenticated with a GitHub account and a valid PAT
#
# Commands to build and push:
#
# docker buildx create --use
# docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/rnacentral/ci-cd:3.20-alpine -f Dockerfile-CI-CD --push .
#
#-------------------------------------------------------------------------------
# Build container with kubectl and helm to be used by GitLab CI/CD

FROM rna-central-ci-cd:3.20-alpine
