version: '2'

services:
  # RNAcentral website
  web:
    build:
      context: .
      dockerfile: Dockerfile-development
    volumes:
      - ${RNACENTRAL_HOME}:/rnacentral/rnacentral-webcode
    ports:
      - "8000:8000"
