version: '3'

services:
  # RNAcentral website
  rnacentral:
    build:
      context: .
      args:
        - LOCAL_DEVELOPMENT=${LOCAL_DEVELOPMENT}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - S3_HOST=${S3_HOST}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
      - EBI_SEARCH_ENDPOINT=${EBI_SEARCH_ENDPOINT}
    expose:
      - 8000
    volumes:
      - static_volume:/srv/rnacentral/static
      - ./openssl/openssl.cnf:/etc/ssl/openssl.cnf
    networks:
      - nginx-network
      - memcached-network

  # Nginx server
  nginx:
    image: nginx:1.24.0-alpine
    ports:
      - 8010:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/srv/rnacentral/static
    depends_on:
      - rnacentral
    networks:
      - nginx-network

  # Memcached server
  memcached:
    image: memcached:1.6.7-alpine
    ports:
      - 11211:11211
    command: memcached -I 5m -m 512m
    depends_on:
      - rnacentral
    networks:
      - memcached-network

volumes:
  static_volume:

networks:
  nginx-network:
    driver: bridge
  memcached-network:
    driver: bridge
