MAPPING = {
    "RNase_MRP_RNA": None,
    "RNase_P_RNA": None,
    "SRP_RNA": None,
    "Y_RNA": None,
    "antisense_RNA": None,
    "autocatalytically_spliced_intron": None,
    "guide_RNA": None,
    "hammerhead_ribozyme": None,
    "lncRNA": None,
    "miRNA": None,
    "misc_RNA": None,
    "ncRNA": None,
    "other": None,
    "piRNA": None,
    "precursor_RNA": None,
    "rasiRNA": None,
    "ribozyme": None,
    "scRNA": None,
    "siRNA": None,
    "snRNA": None,
    "snoRNA": None,
    "telomerase_RNA": None,
    "tmRNA": None,
    "vault_RNA": None,
    'rRNA': 'GO:0005840',
    'tRNA': 'CHEBI:17843',
}
