apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-hh
data:
  HTTP_PROXY: http://hh-wwwcache.ebi.ac.uk:3128
  HTTPS_PROXY: http://hh-wwwcache.ebi.ac.uk:3128
  http_proxy: http://hh-wwwcache.ebi.ac.uk:3128
  https_proxy: http://hh-wwwcache.ebi.ac.uk:3128
  no_proxy: localhost,.cluster.local
