apiVersion: v1
kind: ConfigMap
metadata:
  name: sitemaps-config
data:
  sitemaps.sh: |
    #!/bin/bash
    echo "Creating sitemaps"
    cd $RNACENTRAL_HOME/rnacentral
    rm -fr sitemaps/*
    python manage.py create_sitemaps
    touch rnacentral/wsgi.py
