apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: sitemaps
  name: sitemaps
spec:
  storageClassName: standard-nfs-production
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
