apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: static-volume
  name: static-volume
spec:
  storageClassName: standard-nfs-production
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
