# The HX cluster has 3 workers. Each k8s worker comes with 8 cores and 32GB of RAM.
# The resources of this cluster will be divided as follows:
# - Failover public website (2 workers)
# - Test website (1 worker)

# Database
database: db-dev

# Proxy
proxy: proxy-hx

# EBI search index
searchIndex: search-index-dev

# Install web components
webComponents: "true"

# Create sitemaps
sitemaps: "false"

# Add environment variable
setEnv: "dev"

# Memcached
memcachedReplicas: 1
memcachedRequestsMemory: "512Mi"
memcachedRequestsCPU: "500m"
memcachedLimitssMemory: "1024Mi"

# Redis
redisReplicas: 1
redisRequestsMemory: "1024Mi"
redisRequestsCPU: "500m"
redisLimitssMemory: "2048Mi"

# Nginx
nginxReplicas: 1
nginxRequestsMemory: "512Mi"
nginxRequestsCPU: "500m"
nginxLimitssMemory: "1024Mi"

# RNAcentral
rnacentralReplicas: 1
rnacentralRequestsMemory: "2048Mi"
rnacentralRequestsCPU: "500m"
rnacentralLimitssMemory: "4096Mi"
