# Values used by the test website

# Database
database: db-pro

# EBI search index
searchIndex: search-index-dev

# Install web components
webComponents: "true"

# Create sitemaps
sitemaps: "false"

# Add environment variable
setEnv: "dev"

# Memcached
memcachedRequestsMemory: "4000Mi"
memcachedLimitsMemory: "4000Mi"
memcachedServiceMemory: "3400"

# Nginx
nginxReplicas: 1

# RNAcentral
rnacentralReplicas: 1
