# Database
database: db-pro

# Proxy
proxy: proxy-hh

# EBI search index
searchIndex: search-index-dev

# Install web components
webComponents: "true"

# Create sitemaps
sitemaps: "false"

# Add environment variable
setEnv: "dev"

# Memcached
memcachedReplicas: 1
memcachedRequestsMemory: "6000Mi"
memcachedRequestsCPU: "1000m"
memcachedLimitsMemory: "6000Mi"

# Redis
redisReplicas: 1
redisRequestsMemory: "6000Mi"
redisRequestsCPU: "1000m"
redisLimitsMemory: "6000Mi"

# Nginx
nginxReplicas: 1
nginxRequestsMemory: "4000Mi"
nginxRequestsCPU: "1000m"
nginxLimitsMemory: "4000Mi"

# RNAcentral
rnacentralReplicas: 1
rnacentralRequestsMemory: "16000Mi"
rnacentralRequestsCPU: "1000m"
rnacentralLimitsMemory: "16000Mi"
