# Values used by the test website

# Database
database: db-pro

# Proxy
proxy: proxy-hh

# EBI search index
searchIndex: search-index-dev

# Install web components
webComponents: "true"

# Create sitemaps
sitemaps: "false"

# Add environment variable
setEnv: "dev"

# Memcached
memcachedReplicas: 1
memcachedRequestsMemory: "4000Mi"
memcachedRequestsCPU: "1000m"
memcachedLimitsMemory: "4000Mi"
memcachedServiceMemory: "3400"

# Nginx
nginxReplicas: 1
nginxRequestsMemory: "2000Mi"
nginxRequestsCPU: "1000m"
nginxLimitsMemory: "2000Mi"

# RNAcentral
rnacentralReplicas: 1
rnacentralRequestsMemory: "8000Mi"
rnacentralRequestsCPU: "1000m"
rnacentralLimitsMemory: "8000Mi"
