// submission form
export const FIREBASE_STATUS = 'FIREBASE_STATUS';
export const SET_FIREBASE_ID = 'SET_FIREBASE_ID';
export const SUBMIT_JOB = 'SUBMIT_JOB';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const EXAMPLE_SEQUENCE = 'EXAMPLE_SEQUENCE';
export const CLEAR_SEQUENCE = 'CLEAR_SEQUENCE';
export const TEXTAREA_CHANGE = 'TEXTAREA_CHANGE';
export const TEMPLATE_CHANGE = 'TEMPLATE_CHANGE';
export const SEARCH_METHOD = 'SEARCH_METHOD';
export const INVALID_SEQUENCE = 'INVALID_SEQUENCE';
export const INVALID_DOT_BRACKET = 'INVALID_DOT_BRACKET';
export const TOGGLE_ADVANCED_SEARCH = 'TOGGLE_ADVANCED_SEARCH';
export const TOGGLE_CONSTRAINED_FOLDING = 'TOGGLE_CONSTRAINED_FOLDING';
export const FOLD_TYPE = 'FOLD_TYPE';

// status
export const FETCH_STATUS = 'FETCH_STATUS';
export const SET_JOB_ID = 'SET_JOB_ID';
export const SET_STATUS_TIMEOUT = 'SET_STATUS_TIMEOUT';

// results
export const FETCH_RESULTS = 'FETCH_RESULTS';
export const GET_SVG = 'GET_SVG';
export const SVG_COLORS = 'SVG_COLORS';
export const SVG_NUMBERS = 'SVG_NUMBERS';
export const FASTA = 'FASTA';
export const TSV = 'TSV';
export const UPDATE_SEQUENCE = 'UPDATE_SEQUENCE';
export const URS_RESULTS = 'URS_RESULTS';
