# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20171214_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rnaprecomputeddata',
            name='upi',
        ),
        migrations.AddField(
            model_name='accession',
            name='common_name',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='accession',
            name='standard_name',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='ensemblassembly',
            name='division',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ensemblassembly',
            name='ensembl_url',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ensemblassembly',
            name='example_chromosome',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ensemblassembly',
            name='example_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ensemblassembly',
            name='example_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rnaprecomputed',
            name='update_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='db_xref',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='accession',
            name='note',
            field=models.CharField(max_length=1600),
        ),
        migrations.AlterField(
            model_name='ensemblassembly',
            name='common_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rfamgoterm',
            name='go_term',
            field=models.ForeignKey(db_column=b'go_term_id', on_delete=django.db.models.deletion.CASCADE, related_name='go_term', to='portal.GoTerm'),
        ),
        migrations.AlterField(
            model_name='rnaprecomputed',
            name='rna_type',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='secondarystructure',
            name='accession',
            field=models.OneToOneField(db_column=b'rnc_accession_id', on_delete=django.db.models.deletion.CASCADE, related_name='secondary_structure', to='portal.Accession'),
        ),
        migrations.AlterField(
            model_name='xref',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='RnaPrecomputedData',
        ),
    ]
