# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20171214_1538'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='ensemblassembly',
        #     name='division',
        #     field=models.CharField(db_index=True, max_length=20, null=True),
        # ),
        # migrations.AddField(
        #     model_name='ensemblassembly',
        #     name='ensembl_url',
        #     field=models.CharField(db_index=True, max_length=100, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='ensemblassembly',
        #     name='common_name',
        #     field=models.CharField(db_index=True, max_length=255, null=True),
        # ),
        migrations.AddField(
            model_name='ensemblassembly',
            name='example_chromosome',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ensemblassembly',
            name='example_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ensemblassembly',
            name='example_start',
            field=models.IntegerField(null=True),
        ),
    ]
