# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 13:56
from __future__ import unicode_literals

import caching.base
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_add_genome_mapping_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnsemblKaryotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karyotype', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'ensembl_karyotype',
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
    ]
