# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_auto_20180419_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemblkaryotype',
            name='assembly_id',
            field=models.ForeignKey(db_column=b'assembly_id', default='foobar', on_delete=django.db.models.deletion.CASCADE, related_name='karyotype', to='portal.EnsemblAssembly'),
            preserve_default=False,
        ),
    ]
